
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import ReduxProvider from '@/redux/provider'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

 <html lang="en">
 
  <Navbar/>
      
      <body className={inter.className}>
        <ReduxProvider>{children} </ReduxProvider></body>

      <Footer/>

     
    </html>

   
  )
}
